### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by hadim** [portugueslab/flammkuchen#3]
I have opened a PR to add a conda forge package: https://github.com/conda-forge/staged-recipes/pull/10656

**Comment by hadim** [comment]
ping @vigji

**Comment by hadim** [comment]
Here is the repo: https://github.com/conda-forge/flammkuchen-feedstock

`conda install -c conda-forge flammkuchen` now works.

Once the new version updated to pypi, the conda package should automatically be updated.

**Comment by hadim** [comment]
Anaconda package page: https://anaconda.org/conda-forge/flammkuchen

**Comment by vigji** [comment]
Thanks a lot!
