### ISSUE TITLE
Include license file in pypi archive

### ISSUE THREAD

**Issue by hadim** [portugueslab/flammkuchen#4]
It's a good practice to include the LICENSE file in the source archive of the pypi package.

It's not required for the conda package but it's advised: https://conda-forge.org/docs/maintainer/adding_pkgs.html#packaging-the-license-manually

You could add it using the manifest file of the project, `MANIFEST.in`.

**Comment by vigji** [comment]
Thanks a lot for the advice. Now I should have included it in the manifest file.
