### ISSUE TITLE
List limited to 256 elements?

### ISSUE THREAD

**Issue by hadim** [portugueslab/flammkuchen#5]
I discovered that lists are limited to 256 elements: https://github.com/portugueslab/flammkuchen/blob/ad1d64054f69259e213bfb63d6856f0f32a406d4/flammkuchen/hdf5io.py#L224

Why such a limitation? Is that an HDF5 or PyTables limitation?

It took me hours to discover it. Do you think it's possible to implement a list longer than 256 elements? If you don't I think the lib should raise a warning about it.

**Comment by hadim** [comment]
ping @vigji

**Comment by hadim** [comment]
I removed the 256 conditions and so far it works well... Will submit a PR soon.

**Comment by hadim** [comment]
see https://github.com/portugueslab/flammkuchen/pull/6

**Comment by vigji** [comment]
Thank you very much for spotting and fixing this! And sorry it made you waste your time. Merging and releasing new version now
